#!/bin/sh

echo "
# embedded options to qsub - start with #PBS
# -- our name ---
#PBS -N Job

# -- estimated wall clock time (execution time) --
# -- HH:MM:SS
#PBS -l walltime=00:01:30

# -- run in the current working (submission) directory --
# cd $PBS_O_WORKDIR <--- didn't work !
cd $PWD

# here follow the commands you want to execute
export OMP_NUM_THREADS=$OMP_NUM_THREADS
$1
" | qsub
